-- MySQL Script generated by MySQL Workbench
-- 03/05/20 21:57:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `db_ecommerce` ;

-- -----------------------------------------------------
-- Table `tb_persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_persons` ;

CREATE TABLE IF NOT EXISTS `tb_persons` (
  `idperson` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `desperson` VARCHAR(64) NOT NULL COMMENT '',
  `desemail` VARCHAR(128) NULL DEFAULT NULL COMMENT '',
  `nrphone` BIGINT(20) NULL DEFAULT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idperson`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_addresses` ;

CREATE TABLE IF NOT EXISTS `tb_addresses` (
  `idaddress` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idperson` INT(11) NOT NULL COMMENT '',
  `desaddress` VARCHAR(128) NOT NULL COMMENT '',
  `descomplement` VARCHAR(32) NULL DEFAULT NULL COMMENT '',
  `descity` VARCHAR(32) NOT NULL COMMENT '',
  `desstate` VARCHAR(32) NOT NULL COMMENT '',
  `descountry` VARCHAR(32) NOT NULL COMMENT '',
  `nrzipcode` INT(11) NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idaddress`)  COMMENT '',
  CONSTRAINT `fk_addresses_persons`
    FOREIGN KEY (`idperson`)
    REFERENCES `tb_persons` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_addresses_persons_idx` ON `tb_addresses` (`idperson` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_users` ;

CREATE TABLE IF NOT EXISTS `tb_users` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idperson` INT(11) NOT NULL COMMENT '',
  `deslogin` VARCHAR(64) NOT NULL COMMENT '',
  `despassword` VARCHAR(256) NOT NULL COMMENT '',
  `inadmin` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`iduser`)  COMMENT '',
  CONSTRAINT `fk_users_persons`
    FOREIGN KEY (`idperson`)
    REFERENCES `tb_persons` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_users_persons_idx` ON `tb_users` (`idperson` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_carts` ;

CREATE TABLE IF NOT EXISTS `tb_carts` (
  `idcart` INT(11) NOT NULL COMMENT '',
  `dessessionid` VARCHAR(64) NOT NULL COMMENT '',
  `iduser` INT(11) NULL DEFAULT NULL COMMENT '',
  `idaddress` INT(11) NULL DEFAULT NULL COMMENT '',
  `vlfreight` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idcart`)  COMMENT '',
  CONSTRAINT `fk_carts_addresses`
    FOREIGN KEY (`idaddress`)
    REFERENCES `tb_addresses` (`idaddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_carts_users_idx` ON `tb_carts` (`iduser` ASC)  COMMENT '';

CREATE INDEX `fk_carts_addresses_idx` ON `tb_carts` (`idaddress` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_products` ;

CREATE TABLE IF NOT EXISTS `tb_products` (
  `idproduct` INT(11) NOT NULL COMMENT '',
  `desproduct` VARCHAR(64) NOT NULL COMMENT '',
  `vlprice` DECIMAL(10,2) NOT NULL COMMENT '',
  `vlwidth` DECIMAL(10,2) NOT NULL COMMENT '',
  `vlheight` DECIMAL(10,2) NOT NULL COMMENT '',
  `vllength` DECIMAL(10,2) NOT NULL COMMENT '',
  `vlweight` DECIMAL(10,2) NOT NULL COMMENT '',
  `desurl` VARCHAR(128) NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idproduct`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_cartsproducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cartsproducts` ;

CREATE TABLE IF NOT EXISTS `tb_cartsproducts` (
  `idcartproduct` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcart` INT(11) NOT NULL COMMENT '',
  `idproduct` INT(11) NOT NULL COMMENT '',
  `dtremoved` DATETIME NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idcartproduct`)  COMMENT '',
  CONSTRAINT `fk_cartsproducts_carts`
    FOREIGN KEY (`idcart`)
    REFERENCES `tb_carts` (`idcart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartsproducts_products`
    FOREIGN KEY (`idproduct`)
    REFERENCES `tb_products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_cartsproducts_carts_idx` ON `tb_cartsproducts` (`idcart` ASC)  COMMENT '';

CREATE INDEX `FK_cartsproducts_products_idx` ON `tb_cartsproducts` (`idproduct` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_categories` ;

CREATE TABLE IF NOT EXISTS `tb_categories` (
  `idcategory` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descategory` VARCHAR(32) NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idcategory`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_ordersstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_ordersstatus` ;

CREATE TABLE IF NOT EXISTS `tb_ordersstatus` (
  `idstatus` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `desstatus` VARCHAR(32) NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idstatus`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_orders` ;

CREATE TABLE IF NOT EXISTS `tb_orders` (
  `idorder` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idcart` INT(11) NOT NULL COMMENT '',
  `iduser` INT(11) NOT NULL COMMENT '',
  `idstatus` INT(11) NOT NULL COMMENT '',
  `vltotal` DECIMAL(10,2) NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idorder`)  COMMENT '',
  CONSTRAINT `fk_orders_carts`
    FOREIGN KEY (`idcart`)
    REFERENCES `tb_carts` (`idcart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_ordersstatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `tb_ordersstatus` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_orders_carts_idx` ON `tb_orders` (`idcart` ASC)  COMMENT '';

CREATE INDEX `FK_orders_users_idx` ON `tb_orders` (`iduser` ASC)  COMMENT '';

CREATE INDEX `fk_orders_ordersstatus_idx` ON `tb_orders` (`idstatus` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_productscategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_productscategories` ;

CREATE TABLE IF NOT EXISTS `tb_productscategories` (
  `idcategory` INT(11) NOT NULL COMMENT '',
  `idproduct` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idcategory`, `idproduct`)  COMMENT '',
  CONSTRAINT `fk_productscategories_categories`
    FOREIGN KEY (`idcategory`)
    REFERENCES `tb_categories` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productscategories_products`
    FOREIGN KEY (`idproduct`)
    REFERENCES `tb_products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_productscategories_products_idx` ON `tb_productscategories` (`idproduct` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_userslogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_userslogs` ;

CREATE TABLE IF NOT EXISTS `tb_userslogs` (
  `idlog` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `iduser` INT(11) NOT NULL COMMENT '',
  `deslog` VARCHAR(128) NOT NULL COMMENT '',
  `desip` VARCHAR(45) NOT NULL COMMENT '',
  `desuseragent` VARCHAR(128) NOT NULL COMMENT '',
  `dessessionid` VARCHAR(64) NOT NULL COMMENT '',
  `desurl` VARCHAR(128) NOT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idlog`)  COMMENT '',
  CONSTRAINT `fk_userslogs_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_userslogs_users_idx` ON `tb_userslogs` (`iduser` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `tb_userspasswordsrecoveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_userspasswordsrecoveries` ;

CREATE TABLE IF NOT EXISTS `tb_userspasswordsrecoveries` (
  `idrecovery` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `iduser` INT(11) NOT NULL COMMENT '',
  `desip` VARCHAR(45) NOT NULL COMMENT '',
  `dtrecovery` DATETIME NULL DEFAULT NULL COMMENT '',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idrecovery`)  COMMENT '',
  CONSTRAINT `fk_userspasswordsrecoveries_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_userspasswordsrecoveries_users_idx` ON `tb_userspasswordsrecoveries` (`iduser` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
